### ISSUE TITLE
Tool crashes when in idle

### ISSUE THREAD

**Issue by abhijeetb5** [FsmPro/FsmPro#1]
Hey there,

I am having good time working with this tool and appreciate it's features and functionalities.  Just wanted to record an observation that, tool crashes when it's in idle state. Auto save helps and i don't lose my work.

Thanks,
Abhijeet

**Comment by FsmPro** [comment]
Hi Abhijeet, thanks for the update. This is an issue that some users experience while some just don't. 
We have traced this to autosave. Autosave functionality is enabled by default in the live version. We would give a switch for you to disable and hopefully, that should solve the problem. We shall push the feature in the release scheduled in the last week of September 2020. I'll keep this issue open for now.

Thank you for using FsmPro.

**Comment by FsmPro** [comment]
This has been fixed with the v1.0.1 release. I'm closing this.
