### ISSUE TITLE
File open path always reverts to docs

### ISSUE THREAD

**Issue by donatled** [FsmPro/FsmPro#3]
A more useful direction would be for file open to use the last path opened

**Comment by FsmPro** [comment]
Yes, this makes sense. It should revert to docs only if the last path is not found. This would be implemented in the **1.0.3**.

**Comment by FsmPro** [comment]
Hi @donatled, This has been fixed in the v1.1.0 release. You can get it from the website.

**Comment by FsmPro** [comment]
Closing this
